### ISSUE TITLE
Define CRD representing access rule

### ISSUE THREAD

**Issue by piotrmsc** [ory/oathkeeper-k8s-controller#1]
# Description

Kubernetes controllers react on CR which requires CRD to be definied. As we want to create a k8s controller that will server access rules for oathkeeper based on registered rules via CR, we need to first define the CRD.

Custom resource should reflect access rule API see [here](https://www.ory.sh/docs/oathkeeper/api-access-rules). It may reflect the schema of access rule but perhaps can be simplified.

# Reasons

CRD is required for the controller to run. It is also a contract.

**Comment by aeneasr** [comment]
Awesome! LMK if I can be of any help

**Comment by piotrmsc** [comment]
For sure you will be asked for a review ;-)

**Comment by piotrmsc** [comment]
I think we can close this one, CRD was provided in the merged pr. what do you think @aeneasr ? :)

**Comment by piotrmsc** [comment]
CRD created, shortly there will be a PR with link to oathkeeper rules API as a reference for CRD schema
